AUTHOR = hmartzol

NAME = libftocl.a

SRCDIR = src
INCDIRS = inc
OBJDIR = .obj

CFLAGS = -Wall -Wextra -Werror -g
PINC = ../libft/inc
CLIB = ../libft
LIB = ../libft/libft.a
LLARGS = -lOpenCL -ICL
MLARGS = -framework OpenCL

include ../Makefiles/Makefile.gen
