AUTHOR = hmartzol

NAME = libftjson.a

SRCDIR = src
INCDIRS = inc
OBJDIR = .obj

CFLAGS = -Wall -Wextra -Werror -g
PINC = ../libft/inc
CLIB = ../libft
LIB = ../libft/libft.a

include ../Makefiles/Makefile.gen
