AUTHOR = hmartzol

NAME = libftx2.a

SRCDIR = src
INCDIRS = inc
OBJDIR = .obj

CFLAGS = -Wall -Wextra -Werror -g
LPINC = ../libft/inc ../minilibx_X11
LCLIB = ../libft ../minilibx_X11
LLIB = ../libft/libft.a ../minilibx_X11/libmlx.a
LLARGS = -lXext -lX11
MPINC = ../libft/inc ../minilibx_macos
MCLIB = ../libft ../minilibx_macos
MLIB = ../libft/libft.a ../minilibx_macos/libmlx.a
MLARGS = -framework OpenCL -framework OpenGL -framework AppKit

include ../Makefiles/Makefile.gen
